### ISSUE TITLE
How to create a button to delete a conversation? 

### ISSUE THREAD

**Issue by NikV** [DataMcFly/sms-contact#1]
What would be the best way to delete an individual chat with a user?

**Comment by freekrai** [comment]
You can trigger a delete using `datamcflyRef.remove('id of document');` to make it work first, you'd have to query all threads that were part of that individual chat then remove it. So since we group the conversation by the initial `fromNumber`, you could do  something like this:

```
datamcflyRef.where({'fromNumber':NUMBER}).on("value", function(snapshot) {
   snapshot.forEach( function(chat){
      datamcflyFef.remove( chat.value()._id, function( removed ) {
         console.log('Deleted Document : ', removed.value() );
      });
  });
});
```

**Comment by NikV** [comment]
Thanks for the function! Where would I put this in the code?

**Comment by freekrai** [comment]
You could put it into the chatmanager, you may have to make a few changes to it though as the reference is this.datamcflyRef I think

**Comment by NikV** [comment]
Hmm, all the functions I try to put it in seem to error, even after changing the reference.

**Comment by NikV** [comment]
Made the changes, but seems like it gives an error everywhere I put it in chatmanger.

**Comment by freekrai** [comment]
Can you share your chatmanager and I'll take a look? :)

**Comment by NikV** [comment]
Right now, it currently looks the same as the one in this github repo :)

**Comment by freekrai** [comment]
Ok, you can take a look at this file and go from there https://gist.github.com/freekrai/71de95a4b05b8a48854f

It may a tad rough as I didn't have a chance to test it as I'm mobile this morning :)

**Comment by NikV** [comment]
Getting closer! Getting an error though on 113: Cannot read property 'remove' of undefined

**Comment by freekrai** [comment]
`.remove` is definitely a function in the library, so try now with the latest push.

Just changed the `this.datamcflyRef` to `_this.datamcflyRef`

**Comment by NikV** [comment]
Where did you change that? No change if I replace the normal this. before the remove()

**Comment by freekrai** [comment]
Look at the gist...

**Comment by NikV** [comment]
Woops, sorry, I see that!
